# Generated by Django 3.2.9 on 2021-12-07 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorCornerapi', '0002_category_comment_creatorgroup_group_post_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='creatorgroup',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CreatorCornerapi.creator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
